export {
	API_ORIGIN_ENV_VAR,
	createRepoLensClient,
	resolveApiOrigin,
	type RepoLensClient,
	type RepoLensClientOptions
} from './client';

export type { $defs, components, operations, paths, webhooks } from './schema';

export type {
	AdminFixture,
	AdminOverview,
	Analysis,
	AnalysisFixture,
	AnalysisState,
	ApiError,
	AreaLineCount,
	CompositionExclusion,
	CodeRole,
	Confidence,
	ErrorCode,
	Evidence,
	EvidenceKind,
	EvidenceProvider,
	EvidenceSource,
	ExecutionMetadata,
	Finding,
	FindingCategory,
	FindingState,
	HttpMethodClass,
	HttpOverview,
	LanguageLineCount,
	LatencyPercentile,
	LatencySummary,
	LargestSourceFile,
	RoleLineCount,
	Limitation,
	LineCountSummary,
	LineRange,
	OverviewStatement,
	ProbeStatus,
	ProcessOverview,
	Report,
	RepositoryIdentity,
	RetryPolicy,
	RouteOverview,
	Severity,
	StatusClassCounts,
	SystemProbeResponse,
	TriggerStatus
} from './contract';

export {
	ADMIN_FIXTURES,
	ADMIN_FIXTURE_NAMES,
	ADMIN_OVERVIEW_FIXTURE,
	ADMIN_OVERVIEW_MEMORY_UNAVAILABLE_FIXTURE,
	ANALYSIS_FIXTURES,
	ANALYSIS_FIXTURE_NAMES,
	COMPLETED_REPORT_FIXTURE,
	EVIDENCE_SOURCE_ABSENT_FIXTURE,
	FAILED_PERMANENT_FIXTURE,
	FAILED_RETRIABLE_FIXTURE,
	LOC_UNAVAILABLE_FIXTURE,
	QUEUED_FIXTURE,
	RESOLVING_FIXTURE,
	type AdminFixtureName,
	type AnalysisFixtureName
} from './fixtures';

export {
	ANALYSIS_STATE_LABELS,
	CODE_ROLE_LABELS,
	CONFIDENCE_LABELS,
	ERROR_CODE_LABELS,
	EVIDENCE_KIND_LABELS,
	EVIDENCE_PROVIDER_LABELS,
	FINDING_CATEGORY_LABELS,
	FINDING_STATE_LABELS,
	HANDLED_VARIANTS,
	HTTP_METHOD_CLASS_LABELS,
	PROBE_STATUS_LABELS,
	SEVERITY_LABELS,
	TRIGGER_STATUS_LABELS,
	describeAnalysisState,
	describeCodeRole,
	describeConfidence,
	describeErrorCode,
	describeEvidenceKind,
	describeEvidenceProvider,
	describeFindingCategory,
	describeFindingState,
	describeHttpMethodClass,
	describeProbeStatus,
	describeSeverity,
	describeTriggerStatus,
	unknownVariantLabel,
	type VariantDescriptor
} from './unknown-variant';
